apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: dev
spec:
  selector:
    app: backend # yarbt el service bl pod 
  ports:
    - protocol: TCP
      port: 8000 # port mt3 el service 
      targetPort: 8000 #port fi wst container
       

       # type de service : cluster api : mynjmch user y3ytlou mn bara
       # srevice interne khw
       