apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: dev
data:
  MODEL_SERVICE_URL: "http://model-service:8001"
  JSON_PATH: "/app/data/history_prod.json"
  ENV: "dev"
  DEBUG: "true" 